import {chromium} from 'playwright';import assert from 'node:assert/strict';
const b=await chromium.launch({channel:'msedge',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
const paths=['/','/accounts','/cards','/transfers','/payments','/business','/business/cards','/business/invoicing','/business/payroll','/pricing','/about','/careers','/security','/contact','/missing'];
for(const path of paths){await p.goto('http://127.0.0.1:5174'+path);await p.locator('.initial-loader').waitFor({state:'detached'});assert.equal(await p.locator('main h1').count(),1,path);assert.equal(await p.locator('.site-nav').count(),1);assert.equal(await p.locator('footer').count(),1);console.log('Route passed '+path);}
await p.goto('http://127.0.0.1:5174/accounts');await p.locator('.initial-loader').waitFor({state:'detached'});
for(const theme of ['dark','light']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const width of [1440,1024,768,390,360]){await p.setViewportSize({width,height:1000});if(width<=968)await p.getByRole('button',{name:'Open menu',exact:true}).click();await p.getByRole('button',{name:'Personal',exact:true}).click();await p.waitForTimeout(250);assert.equal(await p.locator('#mega-Personal a').count(),5);assert(await p.locator('.mega-menu').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth}));if(width===1440)await p.screenshot({path:'mega-'+theme+'.png'});await p.keyboard.press('Escape');assert.equal(await p.locator('.mega-menu').count(),0);if(width<=968)await p.getByRole('button',{name:'Close menu',exact:true}).click();console.log(theme+' menu '+width);}}
await p.setViewportSize({width:1440,height:1000});await p.getByRole('button',{name:'Business',exact:true}).click();await p.locator('#mega-Business').getByRole('link',{name:/Corporate Cards/}).click();assert(p.url().endsWith('/business/cards'));assert.equal(await p.locator('.mega-menu').count(),0);assert.equal(await p.locator('.initial-loader').count(),0);await p.goBack();assert(p.url().endsWith('/accounts'));await p.reload();await p.locator('.initial-loader').waitFor({state:'detached'});
await p.getByRole('button',{name:'Company',exact:true}).focus();await p.keyboard.press('ArrowDown');assert(await p.locator('#mega-Company a').first().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');assert.equal(await p.locator('.mega-menu').count(),0);
await p.getByRole('button',{name:'Personal',exact:true}).click();await p.mouse.click(25,500);assert.equal(await p.locator('.mega-menu').count(),0);
await p.locator('footer').getByRole('link',{name:'Growth calculator',exact:true}).click();assert(p.url().endsWith('/#growth'));await p.locator('#growth').waitFor();
await p.locator('footer').getByRole('link',{name:'Contact',exact:true}).click();await p.getByLabel('Name',{exact:true}).fill('Demo User');await p.getByLabel('Email',{exact:true}).fill('demo@example.com');await p.getByLabel('Message',{exact:true}).fill('Test inquiry');await p.getByRole('button',{name:'Preview inquiry'}).click();assert(await p.getByRole('status').isVisible());
await p.locator('.nav-auth').getByRole('button',{name:'Sign In',exact:true}).click();assert(await p.getByRole('dialog').isVisible());await p.keyboard.press('Escape');assert(!(await p.getByRole('dialog').isVisible()));
await p.locator('footer').getByRole('link',{name:'Pricing',exact:true}).click();await p.getByRole('group',{name:'Plan type'}).getByRole('button',{name:'Business',exact:true}).click();await p.getByRole('heading',{name:'Enterprise',exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('Navigation, history, keyboard, forms, pricing and auth demo passed');await b.close();



