import { Link } from 'react-router-dom';
import { motion,useReducedMotion } from 'motion/react';
import { ArrowRight,ArrowUpRight,Layers,Check } from 'lucide-react';
import { pageContent } from '../../data/pages';
import '../../styles/pages.css';
export default function ProductPage({name}){const p=pageContent[name],reduced=useReducedMotion();return <div className="inner-page">
 <motion.section className="product-hero" initial={reduced?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.45}}><div><span className="page-eyebrow">{p.label}</span><h1>{p.title}</h1><p>{p.text}</p><div className="page-actions"><Link className="page-button" to="/contact">{name==='Careers'?'Stay in touch':'Talk to Payline'}<ArrowUpRight size={16}/></Link><Link className="page-link" to={name==='About'||name==='Careers'?'/security':'/pricing'}>{name==='About'||name==='Careers'?'Our approach to trust':'Explore pricing'}<ArrowRight size={15}/></Link></div></div><div className="product-preview" aria-label={`${p.visual}, illustrative preview`}><div className="preview-top"><span className="logo-icon">P</span><span>PAYLINE / {p.label.toUpperCase()}</span></div><div className="preview-orbits" aria-hidden="true"><i/><i/><i/></div><small>{p.visual}</small><strong>{p.amount}</strong><div className="preview-rows">{p.steps.map((step,i)=><div key={step}><span>0{i+1}</span>{step}<Check size={14}/></div>)}</div><span className="preview-note">Illustrative product preview</span></div></motion.section>
 <section className="page-features" aria-label="Highlights">{p.features.map(([title,text])=><article key={title}><Layers size={21}/><h2>{title}</h2><p>{text}</p></article>)}</section>
 <section className="page-next"><div><span className="page-eyebrow">KEEP EXPLORING</span><h2>{name==='Careers'?'A future worth building.':'Your next move starts here.'}</h2><p>{name==='Careers'?'There are no published openings in this demo. Explore our story and check back for updates.':'Discover the rest of the Payline experience, from everyday money to business workflows.'}</p></div><Link className="page-button secondary" to={p.related}>Explore more<ArrowRight size={16}/></Link></section>
 </div>;}
